sudo: true
language: Generic
os:
  - linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - gfortran
    - gcc
    - mpich
    - liblapack-dev
    - liblapacke-dev
    - libmpich-dev
    - libopenblas-dev
    - mpich
install:
  - cd src/;make
script:
  - cd src/;make test
